name: Status Check

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: 

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Tornar script executável
        run: chmod +x ./status-check.sh

      - name: Executar verificação de status
        run: ./status-check.sh 
